### PR TITLE
Add missing nodes to various places in InferenceSystem

### PR DESCRIPTION
**Pull request by dthaler**
Eventually these should all pull from https://live.orcasound.net/api/json/feeds but the first step is to try adding the missing ones manually.

### CODE REVIEW

**Review by micya — COMMENTED** [review]
> "Update the last line of the [Dockerfile](https://github.com/orcasound/aifororcas-livesystem/pull/Dockerfile) to point to the new config file"

In theory, each container should have its own dockerfile. In practice, the original owners used one dockerfile and manually changed the last line before executing `docker build`.

> I do not know how to test this PR.

You should test the individual docker images by running `docker run` locally and verifying that the logs look as expected (does not crash). 

> I am not sure if the github CI/CD workflows exercise these scripts or not.

No CI/CD is currently setup for the inference system. We manually deploy to kubernetes using the instructions [here](https://github.com/orcasound/aifororcas-livesystem/tree/main/InferenceSystem#deploying-an-updated-docker-build-to-azure-kubernetes-service).

Although we no longer deploy on Azure Container Instances, it is good practice to keep the ACI deployment config up to date (as you have done in this PR) in the unlikely chance that Azure fixes the stability issues and we move back to ACI.

**Comment by micya** [comment]
> > > "Update the last line of the [Dockerfile](https://github.com/orcasound/aifororcas-livesystem/pull/Dockerfile) to point to the new config file"
> > 
> > 
> > In theory, each container should have its own dockerfile. In practice, the original owners used one dockerfile and manually changed the last line before executing `docker build`.
> 
> What's confusing in the README is that it implies that the PR should update the Dockerfile. But it sounds like that's not the case. It sounds like the README should be updated to say to not check in the Dockerfile changes, but to do it locally, once for each hydrophone being added, etc. per the explanation you gave in comments above.

Your understanding is correct. The proper fix is to add a dockerfile per location.

**Comment by dthaler** [comment]
> You should test the individual docker images by running docker run locally

I tried following the instructions to do so but couldn't even get far enough to try.  Filed issue #156 which is blocking my ability to test locally.

**Comment by micya** [comment]
I will approve once this PR is tested as noted in https://github.com/orcasound/aifororcas-livesystem/pull/151#discussion_r1688309110.

**Comment by dthaler** [comment]
> I will approve once this PR is tested as noted in [#151 (comment)](https://github.com/orcasound/aifororcas-livesystem/pull/151#discussion_r1688309110).

Testing is currently blocked on #156

**Comment by micya** [comment]
Obsoleted by https://github.com/orcasound/aifororcas-livesystem/pull/197.

**Comment by dthaler** [comment]
> Obsoleted by #197.

Only partially.  There are some things in this PR that are not in 197.  I will rebase.

**Comment by dthaler** [comment]
> > Obsoleted by #197.
> 
> Only partially. There are some things in this PR that are not in 197. I will rebase.

I rebased. @micya  Please re-review.

* Updated README.md so that line 179 need not be modified every time we add a hydrophone
* Updated hls_reader.py to add the commas since the checked-in file is invalid syntax (as reported by CodeQL) and to add the remaining streams
* Updated LiveInferenceOrchestrator.py to alphabetize the list, and also to correct the "name" of Orcasound Lab per issue #145 
* Updated PrepareDataForPredictionExplorer.py to add the missing steams
* Updated globals.py to alphabetize the list

**Review by micya — APPROVED** [review]
No behavior change. Redeployment not required.

**Pull request merged**
